// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdCZ4ryl6p3dH83BC1EphkK7saCqbIxfk',
    appId: '1:434684562078:web:82dea6bdc069d77841898f',
    messagingSenderId: '434684562078',
    projectId: 'pupr-konstruksi-capstone-ce757',
    authDomain: 'pupr-konstruksi-capstone-ce757.firebaseapp.com',
    storageBucket: 'pupr-konstruksi-capstone-ce757.firebasestorage.app',
    measurementId: 'G-5KYZYB7BQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAno0cK5Vm5hqxzMSYXC0EeHV3dxPXCrQA',
    appId: '1:434684562078:android:5521c15437d3796741898f',
    messagingSenderId: '434684562078',
    projectId: 'pupr-konstruksi-capstone-ce757',
    storageBucket: 'pupr-konstruksi-capstone-ce757.firebasestorage.app',
  );

}